# NUMPY

## Creating and Saving NumPy ndarrays

### We import Numpy into Python

In [1]:
import numpy as np

### We create a 1D ndarray that contains only integers

In [2]:
x = np.array([1, 2, 3, 4, 5])

### Let's print the ndarray we just created using the print() command

In [3]:
print('x = ', x)

x =  [1 2 3 4 5]


### We print information about x

In [4]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


You can check out all the different data types NumPy supports in the link below:
[NumPy Data Types](https://www.google.com)


In [5]:
x = np.int64(x)

In [6]:
print(x.dtype)

int64


### We create a rank 1 ndarray that only contains strings

In [7]:
x = np.array(['Hello', 'World'])

### We print x

In [8]:
print()
print('x = ', x)
print()


x =  ['Hello' 'World']



### We print information about x

In [9]:
print('x had dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The element in x are of type: ', x.dtype)

x had dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The element in x are of type:  <U5


### We create a rank 1 ndarray from a Python list that contains integers and strings

In [10]:
x = np.array([1,2, 'World'])

### We print information about x

In [11]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


### We create a rank 2 ndarray that only contains integers

In [12]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

### We print Y

In [13]:
print('Y = \n', Y)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### We print information about Y

In [14]:
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


### We create a rank 1 ndarray that contains integers

In [15]:
x = np.array([1,2,3])

### We create a rank 1 ndarray that contains floats

In [16]:
y = np.array([1.0, 2.0, 3.0])

### We create a rank 1 ndarray that contains integers and floats

In [17]:
z = np.array([1, 2.5, 4])

### We print the dtype of each ndarray

In [18]:
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


### We create a rank 1 ndarray of floats but set the dtype to int64

In [19]:
x = np.array ([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

### We print x

In [20]:
print('x = ', x)

x =  [1 2 3 4 5]


### We print the dtype x

In [21]:
print('The element in x are of type:', x.dtype)

The element in x are of type: int64


### We create a rank 1 ndarray

In [22]:
x = np.array([1,2,3,4,5])

### We save x into the current directory as 

In [23]:
np.save('my_array', x)

### We load the saved array from our current directory into variable y

In [24]:
y = np.load('my_array.npy')

### We print y

In [25]:
print('y = ', y)

y =  [1 2 3 4 5]


### We print information about the ndarray we loaded

In [26]:
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


## Using Built-in Functions to create ndarrays

### We create a 3 x 4 ndarray full of zeros.

In [27]:
X = np.zeros((3,4))

### We print X

In [28]:
print('X = \n', X)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### We print information about X

In [29]:
print('X has dimentions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimentions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


###  We create a 3 x 2 ndarray full of ones. 

In [30]:
X = np.ones((3,2))

### We print X

In [31]:
print('X = \n', X)

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


### We print information about X

In [32]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


###  We create a 2 x 3 ndarray full of fives.

In [33]:
X = np.full((2,3), 5)

### We print X

In [34]:
print('X = \n', X)

X = 
 [[5 5 5]
 [5 5 5]]


### We print information about X

In [35]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


### We create a 5 x 5 Identity matrix. 

In [36]:
X = np.eye(5)

### We print X

In [37]:
print('X = \n', X)

X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### We print information about X

In [38]:
print('X has dimenstions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimenstions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal

In [39]:
X = np.diag([10,20,30,50])

### We print X

In [40]:
print('X = \n',X)

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


###  We create a rank 1 ndarray that has sequential integers from 0 to 9

In [41]:
x = np.arange(10)

### We print the ndarray

In [42]:
print('x = ', x)

x =  [0 1 2 3 4 5 6 7 8 9]


### We print information about the ndarray

In [43]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### We create a rank 1 ndarray that has sequential integers from 4 to 9. 

In [44]:
x = np.arange(4,10)

### We print the ndarray

In [45]:
print('x =',x)

x = [4 5 6 7 8 9]


### We print information about the ndarray

In [46]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.

In [47]:
x = np.arange(1,14,3)

### We print the ndarray

In [48]:
print('x = ',x)

x =  [ 1  4  7 10 13]


### We print information about the ndarray

In [49]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25 with 25 excluded.

In [50]:
x = np.linspace(0,25, 10, endpoint = False)

### We print the ndarray

In [51]:
print('x = \n',x)

x = 
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### We print information about the ndarray

In [52]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


###  We create a rank 1 ndarray with sequential integers from 0 to 19

In [53]:
x = np.arange(20)

### We print x

In [54]:
print('Oranginal x = ', x)

Oranginal x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### We reshape x into a 4 x 5 ndarray 

In [55]:
x = np.reshape(x,(4,5))

###  We print the reshaped x

In [56]:
print('Reshaped x = \n', x)

Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### We print information about the reshaped x

In [57]:
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


### We create a a rank 1 ndarray with sequential integers from 0 to 19 and reshape it to a 4 x 5 array 

In [58]:
Y = np.arange(20).reshape(4,5)

### We print Y 

In [59]:
print('Y = \n', Y)

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


###  We print information about Y

In [60]:
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


###  We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50, with 50 excluded. We then reshape it to a 5 x 2 ndarray

In [61]:
X = np.linspace(0,50,10, endpoint = False). reshape(5,2)

### We print X

In [62]:
print('X = \n', X)

X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


### We print information about X

In [63]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:',X.dtype)

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


###  We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).

In [64]:
X = np.random.randint(4,15,size = (3,2))

###  We print X

In [65]:
print('X = \n', X)

X = 
 [[ 8  7]
 [ 6  5]
 [ 6 11]]


###  We print information about X

In [66]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


###  We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution with a mean of zero and a standard deviation of 0.1.

In [67]:
X = np.random.normal(0,0.1, size=(1000, 1000))

### We print X

In [68]:
print ('X = \n', X)

X = 
 [[-4.97997823e-02  1.06031349e-02  6.90732318e-05 ... -9.05619349e-02
  -1.45346484e-01 -2.48410391e-02]
 [-8.63275973e-02 -8.17725926e-03 -1.88813545e-02 ...  1.65332710e-01
   2.12485116e-01  4.34219618e-02]
 [ 3.91831325e-02  3.88228676e-02  4.34702728e-03 ... -1.30337061e-01
   6.97403817e-02  5.75625274e-03]
 ...
 [ 1.70355134e-01 -4.90196283e-02  7.08846846e-02 ...  2.35982636e-02
  -4.39611192e-02 -3.92010982e-02]
 [ 2.52410964e-02 -2.14707907e-01  1.88969914e-01 ... -1.18564861e-01
   2.03193297e-02  4.02902672e-02]
 [-1.20736173e-01 -5.16108297e-02  1.11271037e-01 ... -7.24319204e-02
  -1.03059896e-01 -5.62992181e-02]]


### We print information about X

In [69]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X<0).sum(),'negative numbers')
print('X has', (X>0).subm(), 'postive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -4.948950758914268e-05
The maximum value in X is: 0.5133753274203988
The minimum value in X is: -0.47656070919745014
X has 500559 negative numbers


AttributeError: 'numpy.ndarray' object has no attribute 'subm'

### Exercise

In [ ]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,34,2).reshape(4,4)
print(X)

## Accessing, Deleting, and Inserting Elements Into ndarrays

### We create a rank 1 ndarray that contains integers from 1 to 5

In [ ]:
x = np.array([1, 2, 3, 4, 5])

### We print x

In [ ]:
print('x = ', x)

### Let's access some elements with positive indices

In [ ]:
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (last) Element in x:', x[4])

### Let's access the same elements with negative indices

In [ ]:
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (last) Element in x:', x[-1])

### We create a rank 1 ndarray that contains integers from 1 to 5

In [ ]:
x = np.array([1, 2, 3, 4, 5])

### We print the original x

In [ ]:
print('Original:\n x = ', x)

### We change the fourth element in x from 4 to 203

In [ ]:
x[3] = 20

### We print x after it was modified 

In [ ]:
print('Modified:\n x = ', x)

### We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9

In [ ]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

### We print X

In [ ]:
print('X = \n', X)

### Let's access some elements in X

In [ ]:
print('This is (0,0) Element in X: ', X[0,0])
print('This is (0,1) Element in X: ', X[0,1])
print('This is (2,2) Element in X: ', X[2,2])

### We change the (0,0) element in X from 1 to 20

In [ ]:
X[0,0] = 20

### We print X after it was modified

In [ ]:
print('Modified:\n X = \n', X)

### We create a rank 1 ndarray

In [ ]:
x = np.array([1, 2, 3, 4, 5])

### We create a rank 2 ndarray

In [ ]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

### We print x

In [ ]:
print('Original x = ', x)

### We delete the first and last element of x

In [ ]:
x = np.delete(x, [0,4])

### We print x with the first and last element deleted

In [ ]:
print('Modified x = ', x)

### We print Y

In [ ]:
print('Original Y = \n', Y)

### We delete the first row of y

In [ ]:
w = np.delete(Y, 0, axis=0)

### We delete the first and last column of y

In [ ]:
v = np.delete(Y, [0,2], axis = 1)

### We print w

In [ ]:
print('w = \n', w)

### We print v

In [ ]:
print('v = \n', v)

### We create a rank 1 ndarray 

In [ ]:
x = np.array([1, 2, 3, 4, 5])

#### We create a rank 2 ndarray 

In [ ]:
Y = np.array([[1,2,3],[4,5,6]])

### We print x

In [ ]:
print('Original x = ', x)

### We append the integer 6 to x

In [ ]:
x = np.append(x, 6)

### We print x

In [ ]:
print ('x = ', x)

### We append the integer 7 and 8 to x

In [ ]:
x = np.append(x, [7,8])

### We print x

In [ ]:
print('x = ', x)

### We print Y

In [ ]:
print('Original Y = \n', Y)

### We append a new row containing 7,8,9 to y

In [ ]:
v = np.append(Y,[[7, 8, 9]], axis=0)

### We append a new column containing 9 and 10 to y

In [ ]:
q = np.append(Y,[[9], [10]], axis = 1)

### We print v

In [ ]:
print('v = \n', v)

### We print q

In [ ]:
print('q = \n', q)

### We create a rank 1 ndarray 

In [ ]:
x = np.array([1, 2, 5, 6, 7])

### We create a rank 2 ndarray

In [ ]:
Y = np.array([[1,2,3],[7,8,9]])

### We print x

In [ ]:
print('Original x = ', x)

### We insert the integer 3 and 4 between 2 and 5 in x.

In [ ]:
x = np.insert(x,2,[3,4])

### We print x with the inserted elements

In [ ]:
print('x = ', x)

### We print Y

In [ ]:
print('Original Y = \n', Y)

### We insert a row between the first and last row of y

In [ ]:
w = np.insert(Y, 1, [4, 5, 6], axis = 0)

### We insert a column full of 5s between the first and second column of y

In [ ]:
v = np.insert(Y,1,5, axis = 1)

### We print w and v

In [ ]:
print('w = \n', w)
print('v = \n', v)

### We create a rank 1 ndarray 

In [ ]:
x = np.array([1,2])

### We create a rank 2 ndarray

In [ ]:
Y = np.array([[3,4],[5,6]])

### We print Y

In [ ]:
print('Y = \n', Y)

### We stack x on top of Y

In [ ]:
z = np.vstack((x,Y))

### We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 

In [ ]:
w = np.hstack((Y,x.reshape(2,1)))

### We print z

In [ ]:
print('z = \n', z)

### We print w

In [ ]:
print('w = \n', w)

# Slicing ndarrays

### We create a 4 x 5 ndarray that contains integers from 0 to 19

In [ ]:
X = np.arange(20).reshape(4,5)

### We print X

In [ ]:
print('X = \n',X)

### We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns

In [ ]:
Z = X[1:4, 2:5]

### We print Z

In [ ]:
print('Z = \n', Z)

### We can select the same elements as above using method 2

In [ ]:
W = X[1:,2:5]

### We print W

In [ ]:
print('W = \n', W)

### We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns

In [ ]:
Y = X[:3, 2:5]

### We print Y

In [ ]:
print('Y = \n', Y)

### We select all the elements in the 3rd row

In [ ]:
v = X[2,:]

### We print v

In [ ]:
print('v = ', v)

### We select all the elements in the 3rd column

In [ ]:
q = X[:,2]

### We print q

In [ ]:
print('q = ', q)

### We select all the elements in the 3rd column but return a rank 2 ndarray

In [ ]:
R = X[:,2:3]

### We print R

In [ ]:
print('R = \n', R)

### We create a 4 x 5 ndarray that contains integers from 0 to 19

In [ ]:
X = np.arange(20).reshape(4,5)

### We print X

In [ ]:
print('X = \n', X)

### We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns

In [ ]:
Z = X[1:4, 2:5]

### We print Z

In [ ]:
print('Z = \n', Z)

### We change the last element in Z to 555

In [ ]:
Z[2,2] = 555

### We print X

In [ ]:
print('X = \n', X)

### We create a 4 x 5 ndarray that contains integers from 0 to 19

In [ ]:
X = np.arange(20).reshape(4,5)

### We print X

In [ ]:
print('X = \n', X)

### create a copy of the slice using the np.copy() function

In [ ]:
Z = np.copy(X[1:4,2:5])

### create a copy of the slice using the copy as a method

In [ ]:
W = X[1:4,2:5].copy()

### We change the last element in Z to 555

In [ ]:
Z[2,2] = 555

### We change the last element in W to 444

In [ ]:
W[2,2] = 444

### We print X

In [ ]:
print('X = \n', X)

### We print Z

In [ ]:
print('Z = \n', Z)

### We print W

In [ ]:
print('W = \n', W)

### We create a 4 x 5 ndarray that contains integers from 0 to 19

In [ ]:
X = np.arange(20).reshape(4, 5)

### We create a rank 1 ndarray that will serve as indices to select elements from X

In [ ]:
indices = np.array([1,3])

### We print X

In [ ]:
print('X = \n', X)

### We print indices

In [ ]:
print('indices = ', indices)

### We use the indices ndarray to select the 2nd and 4th row of X

In [ ]:
Y = X[indices,:]

### We use the indices ndarray to select the 2nd and 4th column of X

In [ ]:
Z = X[:, indices]

### We print Y

In [ ]:
print('Y = \n', Y)

### We print Z

In [ ]:
print('Z = \n', Z)

In [ ]:
We create a 4 x 5 ndarray that contains integers from 0 to 19

In [ ]:
X = np.arange(25).reshape(5, 5)

In [ ]:
We print X

In [ ]:
print('X = \n', X)

In [ ]:
We print the elements in the main diagonal of X

In [ ]:
print('z =', np.diag(X))

In [ ]:
We print the elements above the main diagonal of X

In [ ]:
print('y =', np.diag(X, k=1))

In [ ]:
We print the elements below the main diagonal of X

In [ ]:
print('w = ', np.diag(X, k=-1))

In [ ]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

### We create a 5 x 5 ndarray that contains integers from 0 to 24

In [ ]:
X = np.arange(25).reshape(5, 5)

### We print X

In [ ]:
print('Original X = \n', X)

### We use Boolean indexing to select elements in X:

In [ ]:
print('The elements in X that are greater than 10:', X[X > 10])

In [ ]:
print('The elements in X that less than or equal to 7:', X[X <= 7])

In [ ]:
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

### We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1

In [ ]:
X[(X > 10) & (X < 17)] = -1

### We print X

In [ ]:
print('X = \n', X)

### We create a rank 1 ndarray

In [ ]:
x = np.array([1,2,3,4,5])

### We create a rank 1 ndarray

In [ ]:
y = np.array([6,7,2,8,4])

### We print x

In [ ]:
print('x = ', x)

### We print y

In [ ]:
print('y = ', y)

### We use set operations to compare x and y:

In [ ]:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('The elements that are in x and y:', np.union1d(x,y))

### We create an unsorted rank 1 ndarray

In [ ]:
x = np.random.randint(1,11,size=(10,))

### We print x

In [ ]:
print('Original x = ', x)

### We sort x and print the sorted array using sort as a function.

In [ ]:
print('Sorted x (out of place):', np.sort(x))

### When we sort out of place the original array remains intact. To see this we print x again

In [ ]:
print('x after sorting:', x)

### We sort x but only keep the unique elements in x

In [ ]:
print(np.sort(np.unique(x)))

### We create an unsorted rank 2 ndarray

In [ ]:
X = np.random.randint(1,11,size=(5,5))

### We print X

In [ ]:
print('Original X = \n', X)

### We sort the columns of X and print the sorted array

In [ ]:
print('X with sorted columns :\n', np.sort(X, axis = 0))

### We sort the rows of X and print the sorted array

In [ ]:
print('X with sorted rows :\n', np.sort(X, axis = 1))

# Manipulating ndarrays

### Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).

In [ ]:
X = np.arange(1, 26).reshape(5,5)

In [ ]:
print('X = \n',X)

In [ ]:
Y = X[X % 2 != 0]

In [ ]:
print('Y = \n', Y)

### We create two rank 1 ndarrays

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5.5, 6.5, 7.5, 8.5])

### We print x

In [ ]:
print('x = ', x)

### We print y

In [ ]:
print('y = ', y)

### We perfrom basic element-wise operations using arithmetic symbols and functions

In [ ]:
print('x = y = ', x+y)
print('add(x,y)=', np. add(x,y))
print()
print('x - y = ', x-y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x*y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x/y)
print('divide(x,y) = ', np.divide(x,y))

### We create two rank 2 ndarrays

In [ ]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2,2)

### We print X

In [ ]:
print('X = \n', X)

### We print Y

In [ ]:
print('Y = \n', Y)

### We perfrom basic element-wise operations using arithmetic symbols and functions

In [ ]:
print('x = y = ', X+Y)
print('add(x,y)=', np. add(X,Y))
print()
print('x - y = ', X-Y)
print('subtract(x,y) = ', np.subtract(X,Y))
print()
print('x * y = ', X*Y)
print('multiply(x,y) = ', np.multiply(X,Y))
print()
print('x / y = ', X/Y)
print('divide(x,y) = ', np.divide(X,Y))

### We create a rank 1 ndarray

In [ ]:
x = np.array([1,2,3,4])

### We print x

In [ ]:
print('x = ', x)

### We apply different mathematical functions to all elements of x

In [ ]:
print('EXP(x) = ', np.exp(x))
print('SQRT(x) = ', np.sqrt(x))
print('POW(x, 2) = ', np.power(x,2))

### We create a 2 x 2 ndarray

In [ ]:
X = np.array([[1,2], [3,4]])

x### We print x

In [ ]:
print('X = \n', X)

In [ ]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis = 0))
print('Average of all elements in the rows of X:', X.mean(axis = 1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis = 0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in X:', X.std(axis=0))
print('Standard Deviation of all elements in X:', X.std(axis = 1))
print()
print('Median value of all elements in X:',np.median(X))
print('Median value of all elements in the columns of X:',np.median(X, axis = 0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:',X.max(axis=0))
print('Maximum value of all elements in the rows of X: ', X.max(axis = 1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis = 1))

### We create a 2 x 2 ndarray

In [ ]:
X = np.array([[1, 2], [3, 4]])

### We print x

In [ ]:
print('X = \n', X)

In [ ]:
print('3 * X = \n', 3 * X)

In [ ]:
print('3 + X = \n', 3 + X)

In [ ]:
print('X - 3 = \n', X - 3)

In [ ]:
print('X / 3 = \n', X / 3)

In [ ]:
print('X / 3 = \n', X/3)

### We create a rank 1 ndarray

In [ ]:
x = np.array([1,2,3])

### We create a 3 x 3 ndarray

In [ ]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

### We create a 3 x 1 ndarray

In [ ]:
Z = np.array([1,2,3]).reshape(3,1)

### We print x

In [ ]:
print('x = ', x)

### We print Y

In [ ]:
print('Y = \n', Y)

### We print Z

In [ ]:
print('Z = \n', Z)

In [ ]:
print('x + Y = \n', x + Y)

In [ ]:
print('Z + Y = \n',Z + Y)

In [ ]:
X = np.ones((4,4)) * np.arange(1,5)

In [70]:
print(X)

[[-4.97997823e-02  1.06031349e-02  6.90732318e-05 ... -9.05619349e-02
  -1.45346484e-01 -2.48410391e-02]
 [-8.63275973e-02 -8.17725926e-03 -1.88813545e-02 ...  1.65332710e-01
   2.12485116e-01  4.34219618e-02]
 [ 3.91831325e-02  3.88228676e-02  4.34702728e-03 ... -1.30337061e-01
   6.97403817e-02  5.75625274e-03]
 ...
 [ 1.70355134e-01 -4.90196283e-02  7.08846846e-02 ...  2.35982636e-02
  -4.39611192e-02 -3.92010982e-02]
 [ 2.52410964e-02 -2.14707907e-01  1.88969914e-01 ... -1.18564861e-01
   2.03193297e-02  4.02902672e-02]
 [-1.20736173e-01 -5.16108297e-02  1.11271037e-01 ... -7.24319204e-02
  -1.03059896e-01 -5.62992181e-02]]
